apiVersion: v1
kind: Service
metadata:
  name: sse-service
  labels:
    app: sse
spec:
  type: {{ .Values.service.type }}
  selector:
    app: sse
  ports:
    - port: 80
      targetPort: {{ .Values.service.port }}

