apiVersion: apps/v1
kind: Deployment
metadata:
  name: console-web
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: console-web
  template:
    metadata:
      labels:
        app: console-web
    spec:
      serviceAccountName: console-web
      containers:
        - name: console-web
          image: ghcr.io/sungeunsong/console-web:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: console-web-lb
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: console-web
  ports:
    - port: 80
      targetPort: 3000

