apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: console-web-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: console-web
    namespace: default
roleRef:
  kind: ClusterRole
  name: console-web-clusterrole
  apiGroup: rbac.authorization.k8s.io

