apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: console-web-clusterrole
rules:
  - apiGroups: [""]
    resources:
      - secrets
      - namespaces
      - services
      - pods
    verbs: ["get", "list", "create"]

  - apiGroups: ["apps"]
    resources:
      - deployments
      - statefulsets
      - replicasets
    verbs: ["get", "list", "create"]

  - apiGroups: ["batch"]
    resources:
      - jobs
    verbs: ["get", "list", "create", "delete"]

